### PR TITLE
Suggestions for structuring the project

### PR DESCRIPTION
**Pull request by alextremblay**
Hi Russell, in the below commits I've made a number of changes to align your project with some industry standards. Here's an outline of the changes and their reasons:

CHANGE: replace setup.py with setup.cfg, leveraging the PyScaffold packaging tool
REASON: The PyScaffold model is one of the most popular methods for maintaining python packaging best practices in terms of managing metadata, dev dependencies, and package dependencies. The benefits of this approach are numerous (see [PyScaffold](https://pyscaffold.readthedocs.io/en/latest/features.html) for details), but the big ones for this project are:
 - Any user who downloads this project can do a `pip install -e .` and pip will automatically install all project dependencies
 - This setup.cfg file is configured to leverage git for versioning. A common industry best-practice is to tag all python package releases in git with a tag representing the version number. (ex. you release a version 0.0.2 of the bamcli, you tag the git repo at that exact moment with a tag v0.0.2). That way, anyone can at any point in time easily go back to the source code exactly as it was when that version of the package was published. Normally, this is a two-step process (increase the version number in setup.py / setup.cfg, then git tag the repo with that version) This particular setup.py file automatically infers the package version from the git tag, so that any time you create a git tag containing a version number (v0.0.2 for example), the version of the python package will automatically update, saving you an extra step
 - If this project were to be built into a distributable package and published to a package index like PYPI, the contents of the README would be included in the long description. you don't need to maintain a separate copy of the README just for PYPI
 - all development metadata for the package and the development environmnet, and any future documentation and testing tooling you might use are all in one place, easy to manage

CHANGE: replace HTML code in the README with markdown
REASON: markdown syntax confers a number of benefits over HTML:
 - It's easier to read and write in its raw form
 - When section headers are expressed in markdown instead of HTML, it's easier for all markdown processors to parse them and infer document structure. HTML is only useful for web broswers. markdown is useful for web browsers (through auto-renderers like github), as well as terminal markdown viewers, table-of-contents generators, etc
 - when code blocks are expressed as markdown, it's possibly to automatically enable language-aware syntax highlighting in all mardown viewers by specifying (in markdown) what language a code block is written in

CHANGE: rename bamcli.py and pybam.py to bluecat_am.cli and bluecat_am.api
REASON: converting these two scripts into modules in a python package will make it much easier to maintain the code as it grows in size and complexity. making this change early, before it becomes absolutely necessary, will save a lot of headaches in the future. naming the modules cli and api makes it very clear to all what each of these modules does. This will make it easier for any external developers wishing to use the api without the cli to do so.

CHANGE: move the bluecat_am package into a src/ folder
REASON: if / when you start writing automatic tests for this project (using pytest or nose or unittests), you will most likely eventually come to a situation where your tests will fail to capture a certain class of bugs that may crop up in the wild. Isolating your package "bluecat_am" from your project folder solves these problems. For more details on the whys and hows, i suggest reading this excellent [blog post](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure)

CHANGE: add a .gitignore
REASON: as different developers with different tool chains and environments start working on and modifying the project, they will each use tools that add certain developer-specific of machine-specific or build-artifact-specific files to the project folder, files which do not belong in version control. This .gitignore files covers all the most common of these file types for a variety of python development workflows

I hope you find these changes as useful as I do. If you have any questions, please let me know.

Thanks

### CODE REVIEW

**Comment by quistian** [comment]
Great! Thanks. I was planning on removing some of the Library functions I tested but do not use.

Will look at your recommendations.

Russell

Russell P. Sutherland           Email: russell . sutherland @ utoronto dawt ca
Network Engineer, I+TS       Voice: +1.416.978.0470
4 Bancroft Ave., Rm. 102      Cell: +1.416.803.0080
University of Toronto            Fax:   +1.416.978.6620
Toronto, ON  M5S 1C1
________________________________

**Review by quistian — APPROVED** [review]
Got it. Simple change. Commiting.

**Review by quistian — APPROVED** [review]
Knew nothing about the format of this file nor Markdown.

**Review by quistian — APPROVED** [review]
More education here for me. Thanks.

**Review by quistian — APPROVED** [review]

**Review by quistian — APPROVED** [review]
Yes... Better

**Review by quistian — APPROVED** [review]
Here we go...

**Comment by quistian** [comment]
Thanks... Will look at the damage.

**Comment by quistian** [comment]
Re. CHANGE: rename bamcli.py and pybam.py to bluecat_am.cli and bluecat_am.api
REASON: converting these two scripts into modules in a python package will make it much easier to maintain the code as it grows in size and complexity. making this change early, before it becomes absolutely necessary, will save a lot of headaches in the future. naming the modules cli and api makes it very clear to all what each of these modules does. This will make it easier for any external developers wishing to use the api without the cli to do so.

This is a code recommendation? As the code tree stands now it looks like:

```
$ du -ah src
4.0K    src/bluecat_am/__init__.py
76.0K   src/bluecat_am/api.py
4.0K    src/bluecat_am/cli.py
88.0K   src/bluecat_am
92.0K   src

```
I can easily rename the files under git:
```
$ git mv cli.py bluecat_am.cli
$ git mv api.py bluecat_am.api

**Comment by alextremblay** [comment]
`src/bluecat_am/api.py` is `bluecat_am.api`.

Same goes for the cli.

The file `src/bluecat_am/__init__.py` denoted that this folder is a python package. What this means is that when you tell python to import `bluecat_am.cli`, it knows to look for a python package folder called `bluecat_am`, and load a module called `cli.py` from it.

[Here](https://realpython.com/python-modules-packages/)'s an excellent write-up on how that works

**Comment by quistian** [comment]
Ah so! Make's sense. Thanks for the link. I my reading I have not yet got to Py Packages. Still on the Module unit

**Pull request merged**
